[package]
name = "helloworld"
version = "0.0.1"
authors = ["imthaghost <imthaghost@protonmail.com>"]
keywords = ["rust"]
description = "A place for learning Rust"
license = "MIT"
repository = "https://github.com/imthaghost/rustland.git"
readme = "README.md"
exclude = ["docs/*"]